name: tests
"on":
  push:
    branches: [ main, master ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Fast Tests & Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install lint tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy

      - name: Run clang-tidy (header-only check)
        run: |
          mkdir -p ci_logs
          # Simple header-only clang-tidy checks without full compilation
          echo "Running basic clang-tidy checks on headers..."
          find src -name "*.hpp" -type f | head -10 | while read file; do
            echo "Checking $file..."
            clang-tidy "$file" --checks='-*,readability-*,modernize-*' -- -std=c++17 2>&1 | tee -a ci_logs/clang-tidy.txt || true
          done
          if [ -f scripts/clang_tidy_check.py ]; then
            echo "⚠️ Note: Full clang-tidy analysis requires compilation - moved to build.yml"
          else
            echo "✅ Basic header analysis complete"
          fi

      - name: Check for exception policy violations
        run: |
          mkdir -p ci_logs
          echo "Checking core performance modules for exception policy violations..."
          if grep -r "throw" src/media_io src/decode src/playback src/audio src/render src/fx src/cache src/gfx --include="*.cpp" --include="*.hpp" | grep -v "// EXCEPTION_POLICY_OK"; then
            echo "❌ Exception policy violation found in core performance modules!"
            echo "Core modules (media_io, decode, playback, audio, render, fx, cache, gfx) must remain exception-free per DR-0003"
            echo "Exception policy violation found" | tee ci_logs/exception-policy.txt
            exit 1
          else
            echo "✅ Exception policy check passed"
            echo "Exception policy check passed" | tee ci_logs/exception-policy.txt
          fi

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: ci_logs
          retention-days: 7
